<?PHP

echo "<form name=\"previewForm\" action=\"phpsane.php\" method=get>\n";
echo "<input type=hidden name=\"lang\" value=\"".$lang."\">\n";
echo "<input type=hidden name=\"aktion\" value=\"scan\">\n";
echo "<input type=hidden name=\"sid\" value=\"$sid\">\n";
echo "<input type=hidden name=\"scanner\" value=\"$scanner\">\n";
echo "<table>\n";
echo "<tr><td valign=top>\n";
echo "<table>\n";
echo "<tr><td>\n";
if($lang=="en") echo "<b>X-Offset:</b>\n";
if($lang=="de") echo "<b>Links:</b>\n";
echo "</td><td>\n";
echo "<input type=text name=\"geometry_l\" value=\"0\" size=4 maxlength=3>&nbsp;mm\n";
echo "</td></tr><tr><td>\n";
if($lang=="en") echo "<b>Y-Offset:</b>\n";
if($lang=="de") echo "<b>Oben:</b>\n";
echo "</td><td>\n";
echo "<input type=text name=\"geometry_t\" value=\"0\" size=4 maxlength=3>&nbsp;mm\n";
echo "</td></tr><tr><td>\n";
if($lang=="en") echo "<b>Width:</b>\n";
if($lang=="de") echo "<b>Breite:</b>\n";
echo "</td><td>\n";
echo "<input type=text name=\"geometry_x\" value=\"0\" size=4 maxlength=3>&nbsp;mm\n";
echo "</td></tr><tr><td>\n";
if($lang=="en") echo "<b>Height:</b>\n";
if($lang=="de") echo "<b>H&ouml;he:</b>\n";
echo "</td><td>\n";
echo "<input type=text name=\"geometry_y\" value=\"0\" size=4 maxlength=3>&nbsp;mm\n";
echo "</td></tr><tr><td colspan=2>\n";
echo "<script language=\"JavaScript\" type=\"text/javascript\">\n";
echo "<!--\n";
echo "function setGeometry(l,t,x,y) {\n";
echo "document.previewForm.geometry_l.value = l;\n";
echo "document.previewForm.geometry_t.value = t;\n";
echo "document.previewForm.geometry_x.value = x;\n";
echo "document.previewForm.geometry_y.value = y;\n";
echo "}\n";
echo "//-->\n";
echo "</script>\n";
echo "<a href=\"javascript:setGeometry('0','0','210','297')\">DIN-A4</a>\n";
echo "</td></tr><tr><td>\n";
if($lang=="en") echo "<b>Resolution:</b>\n";
if($lang=="de") echo "<b>Aufl&ouml;sung:</b>\n";
echo "</td><td>\n";
echo "<input type=text name=\"resolution\" value=\"150\" size=4 maxlength=3>&nbsp;DPI\n";
echo "</td></tr><tr><td>\n";
echo "<b>Modus:</b>\n";
echo "</td><td>\n";
echo "<select name=\"mode\" size=1>\n";
if($lang=="en") echo "<option value=\"Lineart\">b/w\n<option value=\"Gray\" selected>Gray\n<option value=\"Color\">Color\n";
if($lang=="de") echo "<option value=\"Lineart\">s/w\n<option value=\"Gray\" selected>Grau\n<option value=\"Color\">Farbe\n";
echo "</select>\n";
echo "</td></tr><tr><td colspan=2>\n";
echo "<br>\n";
if($lang=="en") echo "<input type=reset value=\"Reset\"><br><input type=submit value=\"Scan\">\n";
if($lang=="de") echo "<input type=reset value=\"Zur&uuml;cksetzen\"><br><input type=submit value=\"Scannnen\">\n";
echo "</td></tr>\n";
echo "</table>\n";
echo "</form>\n";
echo "</td><td width=100>&nbsp;\n";
echo "</td><td valign=top>\n";
if($preview==1) {
echo "<form name=\"previewImage\" action=\"#\">\n";
$file_pnm=$TMP_PRAEFIX."_".$sid."_preview.pnm";
$file_jpg=$PHPSANE_ROOT."/tmp/".$sid."_preview.jpg";
$file_url="tmp/".$sid."_preview.jpg";
$cmd_scan = $SCANIMAGE." -d ".$scanner." --mode Gray --resolution 15dpi --speed Fastest --preview=yes --fast-preview=yes -l 0mm -t 0mm -x ".$PREVIEW_WIDTH_MM."mm -y ".$PREVIEW_HEIGHT_MM."mm >".$file_pnm;
$cmd_pnmtojpeg = $PNMTOJPEG." --quality=50 --greyscale ".$file_pnm." >".$file_jpg;
$cmd_clean = "rm -f ".$file_pnm;
$scan=`$cmd_scan`;
$pnmtojpeg=`$cmd_pnmtojpeg`;
$clean=`$cmd_clean`;
echo "<input type=radio name=\"ecke\" value=\"lo\" checked>&nbsp;";
if($lang=="en") echo "Top-Left<br>\n";
if($lang=="de") echo "Oben-Links<br>\n";
echo "<input type=radio name=\"ecke\" value=\"ru\">&nbsp;";
if($lang=="en") echo "Bottom-Right<br>\n";
if($lang=="de") echo "Unten-Rechts<br>\n";
echo "<script language=\"JavaScript\" type=\"text/javascript\">\n";
echo "<!--\n";
echo "function setPreview(x,y) {\n";
echo "if(document.previewImage.ecke[1].checked) {\n";
echo "var newL = document.previewForm.geometry_l.value;\n";
echo "var newT = document.previewForm.geometry_t.value;\n";
echo "var newX = x - newL;\n";
echo "var newY = y - newT;\n";
echo "setGeometry(newL,newT,newX,newY);\n";
echo "document.previewImage.ecke[0].checked = true;\n";
echo "}\n";
echo "else {\n";
echo "var newL = x;\n";
echo "var newT = y;\n";
echo "var newX = document.previewForm.geometry_x.value;\n";
echo "var newY = document.previewForm.geometry_y.value;\n";
echo "setGeometry(newL,newT,newX,newY);\n";
echo "document.previewImage.ecke[1].checked = true;\n";
echo "}\n";
echo "}\n";
echo "//-->\n";
echo "</script>\n";
echo "<map name=\"Preview\">\n";
for($y=1;$y<=$PREVIEW_HEIGHT_PX;$y++) {
for($x=1;$x<=$PREVIEW_WIDTH_PX;$x++) {
$xMM = round($x*($PREVIEW_WIDTH_MM/$PREVIEW_WIDTH_PX));
$yMM = round($y*($PREVIEW_WIDTH_MM/$PREVIEW_WIDTH_PX));
echo "<area shape=rect coords=\"".$x.",".$y.",".$x.",".$y."\" href=\"javascript:setPreview(".$xMM.",".$yMM.")\">\n";
}
}
echo "</map>\n";
echo "<br>\n";
echo "<img src=\"".$file_url."\" alt=\"Preview\" width=".$PREVIEW_WIDTH_PX." height=".$PREVIEW_HEIGHT_PX." border=0 usemap=\"#Preview\">\n";
echo "</form>\n";
}
echo "</td></tr>\n";
echo "</table>\n";
?>
